### ISSUE TITLE
Search Bar doesn't appear in iOS7

### ISSUE THREAD

**Issue by deyil** [kentnguyen/KNMultiItemSelector#17]
I have tried this great lib in iOS7 only and unfortunately when enabling search bar, the bar doesn't appear. Only the an empty rectangle area of the bar as it can be seen and in the attached image.
![screen shot 2013-08-12 at 9 15 50](https://f.cloud.github.com/assets/872880/949315/4d22c60c-037b-11e3-8d03-963a20f2b1af.png)

**Comment by bassrock** [comment]
I sent a pull request that fixes this #13

**Comment by henriquezago** [comment]
I'm still having this exact same problem.
