### ISSUE TITLE
Limit Selection?

### ISSUE THREAD

**Issue by VeeruPV** [kentnguyen/KNMultiItemSelector#6]
Thanks for this really wonderful share, i will definitely buy you a coffee :)

Was wondering, if there is an inbuilt feature to limit the number of items to select?

Thanks

**Comment by bassrock** [comment]
+1

**Comment by DK1DA** [comment]
It's just waiting to be pulled ;-)
https://github.com/kentnguyen/KNMultiItemSelector/pull/10

**Comment by kentnguyen** [comment]
Thanks @kimar . Closing this ticket.
