### ISSUE TITLE
No easy way to update the items list

### ISSUE THREAD

**Issue by rnaud** [kentnguyen/KNMultiItemSelector#7]
Hello,

I'm trying to subclass the selector to add the logic to fetch the user list from the controller. But then there is no easy way to update the table with the new items.

I tried reimplementing some part of the init method with no luck, the controller either crashes at the load or when I try to to a search.

Thanks for your help !

**Comment by kentnguyen** [comment]
Are you new to TableViewController? What you describe seems like a typical custom implementation of tableview. You probably need to master that in a separate project first before you can subclass this one.

**Comment by rnaud** [comment]
Hello Kent, no problem with UITableView, sorry if I'm not clear enough. 
Here a [self.tableview reloadData] won't suffice.

The way my controller works: 
You open the modal, the table view is empty and I show an activity label, I do a server load of the user list. 
Then I create all the KNSelectorItem. 
I then copy the results to items (NSMutableArray). But I need to reset the recentItems and the indices. 
No matter what I do, something end up crashing.

**Comment by kentnguyen** [comment]
Ok could you make your code public as part of the public fork?  Or send a gist link here

**Comment by rnaud** [comment]
Sure, here is the gist: https://gist.github.com/3458668

**Comment by kentnguyen** [comment]
I don't see anything seriously wrong with the code. I suggest you turn on "All Objective-C" breakpoint to see exactly what caused the crash. I noticed that you are using Three20 which is a huge bloated library which could interfere a lot with normal TableView.
